import './globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className="dark:bg-gray-900 xl:max-w-4xl container container-fluid mx-auto ">{children}</body>
        </html>
    )
}
